# Generated by Django 6.0.4 on 2026-04-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='bio',
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото (URL)'),
        ),
    ]
