# Generated by Django 6.0.4 on 2026-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_remove_master_bio_alter_master_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Фото'),
        ),
    ]
